version: "3.9"
services:
  database:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cobalt
    ports:
      - "5433:5432"
