// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Ancestor from "@rescriptbr/ancestor/src/Ancestor.bs.js";

function VideoGrid(Props) {
  return React.createElement(Ancestor.Default.Box.make, {
              bgColor: [Ancestor.Default.xs({
                      NAME: "hex",
                      VAL: "#eee"
                    })],
              px: [Ancestor.Default.xs(3)],
              py: [Ancestor.Default.xs(4)],
              children: "Video Grid"
            });
}

var make = VideoGrid;

export {
  make ,
  
}
/* react Not a pure module */
