// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header from "../components/Header.bs.js";
import * as Ancestor from "@rescriptbr/ancestor/src/Ancestor.bs.js";
import * as VideoGrid from "../components/VideoGrid.bs.js";

function FrontPage(Props) {
  return React.createElement(Ancestor.Default.Box.make, {
              children: null
            }, React.createElement(Header.make, {}), React.createElement(Ancestor.Default.Box.make, {
                  minH: [Ancestor.Default.xs({
                          NAME: "pct",
                          VAL: 100.0
                        })],
                  children: React.createElement(VideoGrid.make, {})
                }));
}

var make = FrontPage;

export {
  make ,
  
}
/* react Not a pure module */
