// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Ancestor from "@rescriptbr/ancestor/src/Ancestor.bs.js";

function App(Props) {
  return React.createElement(Ancestor.Default.Grid.make, {
              children: null
            }, React.createElement(Ancestor.Default.Box.make, {
                  display: [{
                      NAME: "xs",
                      VAL: "flex"
                    }],
                  alignItems: [{
                      NAME: "xs",
                      VAL: "center"
                    }],
                  px: [
                    {
                      NAME: "xs",
                      VAL: 8
                    },
                    {
                      NAME: "md",
                      VAL: 12
                    }
                  ],
                  mt: [{
                      NAME: "xs",
                      VAL: 12
                    }],
                  columns: [
                    {
                      NAME: "xs",
                      VAL: 12
                    },
                    {
                      NAME: "md",
                      VAL: 6
                    },
                    {
                      NAME: "lg",
                      VAL: 4
                    }
                  ],
                  children: "Hello"
                }), React.createElement(Ancestor.Default.Box.make, {
                  display: [{
                      NAME: "xs",
                      VAL: "flex"
                    }],
                  alignItems: [{
                      NAME: "xs",
                      VAL: "center"
                    }],
                  py: [
                    {
                      NAME: "xs",
                      VAL: 6
                    },
                    {
                      NAME: "md",
                      VAL: 8
                    }
                  ],
                  m: [{
                      NAME: "xs",
                      VAL: 12
                    }],
                  columns: [
                    {
                      NAME: "xs",
                      VAL: 12
                    },
                    {
                      NAME: "md",
                      VAL: 6
                    },
                    {
                      NAME: "lg",
                      VAL: 4
                    }
                  ],
                  children: "World"
                }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
