// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FrontPage from "./pages/FrontPage.bs.js";

function App(Props) {
  return React.createElement(FrontPage.make, {});
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
