name: build-docker-image
on: [push]
jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        -
          name: Build and push server image
          uses: docker/build-push-action@v3.1.1
          with:
            push: true
            tags: omnisci3nce/cobalt-server:latest
            file: prod.Dockerfile
